---
matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      language: bash
      env:
        - CHANGE_MINIKUBE_NONE_USER=true
        - TRANSMUTE_CRITOOLS_VERSION='v1.11.1'
        - TRANSMUTE_HELM_VERSION='v2.11.0'
        - TRANSMUTE_KUBE_VERSION='v1.11.3'
        - TRANSMUTE_MINIKUBE_VERSION='v0.28.2'

before_script:
  # Installing socat
  - sudo apt-get update -qq
  - sudo apt-get install socat -qq

  # Installing cri-tools
  - curl -Lo crictl.tar.gz "https://github.com/kubernetes-sigs/cri-tools/releases/download/$TRANSMUTE_CRITOOLS_VERSION/crictl-$TRANSMUTE_CRITOOLS_VERSION-linux-amd64.tar.gz"
  - tar -xzvf crictl.tar.gz
  - sudo mv ./crictl /usr/local/bin/crictl
  - rm crictl.tar.gz

  # Installing kubectl
  - curl -Lo kubectl "https://storage.googleapis.com/kubernetes-release/release/$TRANSMUTE_KUBE_VERSION/bin/linux/amd64/kubectl"
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl

  # Installing Minikube
  - curl -Lo minikube "https://storage.googleapis.com/minikube/releases/$TRANSMUTE_MINIKUBE_VERSION/minikube-linux-amd64"
  - chmod +x ./minikube
  - sudo mv ./minikube /usr/local/bin/minikube

  # Starting Minikube
  - sudo minikube start --vm-driver=none --kubernetes-version="$TRANSMUTE_KUBE_VERSION"
  - minikube update-context
  - JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}'
  - until kubectl get nodes -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do sleep 1; done

  # Installing Helm
  - curl -Lo get_helm.sh "https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get"
  - chmod +x ./get_helm.sh
  - ./get_helm.sh --version "$TRANSMUTE_HELM_VERSION"

  # Starting Helm
  - helm init --wait

script:
  - helm install --name dapp-storage ./charts/ipfs
  - helm install --name ethereum-testnet ./charts/ganache
  - helm install --name transmute-api ./charts/api
  - kubectl get services
