version: '2'

services:
  api:
    tty: true # Enables debugging capabilities when attached to this container.
    image: 'bitnami/express:latest'
    labels:
      kompose.service.type: nodeport
    environment:
      - PORT=3000
      - NODE_ENV=development
    ports:
      - 3000:3000
    volumes:
      - .:/app