apiVersion: v1
kind: Service
metadata:
  name: ipfs-gateway-balancer
  labels:
    app: nginx
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-shape: 400Mbps
spec:
  selector:
      app: ipfs
  type: LoadBalancer
  ports:
  - name: gateway
    port: 80
    targetPort: 8080