#!/bin/bash

echo 'Configure IPFS: 💎 + ☁️'

export IPFS_POD_NAME=$(kubectl get pods --namespace default -l "app=ipfs,release=ipfs"  -o jsonpath="{.items[0].metadata.name}")
kubectl exec $IPFS_POD_NAME -- ipfs config Addresses.API /ip4/0.0.0.0/tcp/5001
sleep 2
kubectl exec $IPFS_POD_NAME -- ipfs config --json API.HTTPHeaders.Access-Control-Allow-Origin '["*"]'
sleep 2
kubectl exec $IPFS_POD_NAME -- ipfs config --json API.HTTPHeaders.Access-Control-Allow-Methods '["PUT", "GET", "POST"]'
sleep 2
kubectl delete pod $IPFS_POD_NAME 